# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    image: my-own-autogpt:latest
    env_file:
      - .env
    volumes:
      - "./workspace:/app/auto_gpt_workspace/" 
      - "./workspace:/app/autogpt/auto_gpt_workspace/"
      - "./plugins:/app/plugins/"
      - "./personas:/app/personas"
    profiles: ["exclude-from-up"]
